#!/bin/sh
set -e

# make folders if them doesn't exist
mkdir -p /config/php/php83 \
  /config/log/php/php83

# create local php.ini if it doesn't exist, set local timezone
if [[ ! -f /config/php/php83/php-local.ini ]]; then
    printf "; Edit this file to override php.ini directives\\n\\ndate.timezone = %s\\n" "$TZ" > /config/php/php83/php-local.ini
fi

# symlink user php-local.ini to image
rm -rf /etc/php83/conf.d/php-local.ini
ln -s /config/php/php83/php-local.ini /etc/php83/conf.d/php-local.ini

# create override for www.conf if it doesn't exist
if [[ ! -f /config/php/php83/www2.conf ]]; then
    printf "; Edit this file to override www.conf and php-fpm.conf directives and restart the container\\n\\n; Pool name\\n[www]\\n\\n" >/config/php/php83/www2.conf
fi

# copy user www2.conf to image
rm -rf /etc/php83/php-fpm.d/www2.conf
ln -s /config/php/php83/www2.conf /etc/php83/php-fpm.d/www2.conf

# permissions
chmod -R 777 \
    /config/php \
    /config/log

# first arg is `-f` or `--some-option` or `something.conf`
if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
	set -- php-fpm83 "$@"
fi

exec "$@"